---
- name: Setup Nginx on EC2 instance
  hosts: root
  become_user: root
  become_method: sudo
  tasks:
    - name: Update apt repository and install prerequisites
      apt:
        update_cache: yes
        name: 
          - nginx
        state: latest

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
